version: '3.8'

services:
  swing-tracker:
    container_name: swing-tracker
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
      - '/app/node_modules'
    ports:
      - '3000:3000'
    expose:
      - '3000'